version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app.log:/app/app.log
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    build:
      context: .
      dockerfile: Loki.Dockerfile
    privileged: true
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./app.log:/app/app.log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
